[plugin]
repository = "https://github.com/dohwaplugins/FantasyPlayer.git"
commit = "ff4475a47e55fe3f9a4fbcfa659858613c902967"
owners = [
    "dohwaplugins",
		"KangDohwa",
]
project_path = "FantasyPlayer"
changelog = "Updated for Dalamud staging."
