name: PAC periodic notification

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * *'

jobs:
  runjob:
    if: github.repository == 'dohwaprivate/DalamudPluginsD17'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dohwaprivate/PAC-Nag@8aebccf83df73bf5a11894d2d5832712f941f19d
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          discord_webhook: ${{secrets.PAC_DISCORD_WEBHOOK}}
          pacsheetslink: ${{secrets.PAC_SHEETS_LINK}}